#!/usr/bin/env php
<?php

function show($data)
{
    $args   = func_get_args();

    // Print Multiple values
    if(count($args) > 1) {
        $prints = array();

        $i = 1 ;
        foreach( $args as $arg ):
            $prints[] = "[Value " . $i . "]\n" . print_r($arg, 1);
            $i++ ;
        endforeach;

        echo '<pre>'.implode("\n\n", $prints).'</pre>' ;
    }else{
        // Print one value.
        echo '<pre>'.print_r($data, 1).'</pre>' ;
    }
}

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
